### ISSUE TITLE
Broken on latext nyxt-3 from git 

### ISSUE THREAD

**Issue by shaunsingh** [atlas-engineer/nx-ace#2]
Has the following error: 
```
Warning: The name "NX-ACE" does not designate any package.
Warning: Error on seperate thread: The value 
   &quot;NX-ACE&quot;
is not of type 
   SYMBOL
Warning: Error on separate thread: There is no applicable method for the generic function
   #&lt;STANDARD-GENERIC-FUNCTION NYXT:BUFFER (20)&gt;
when called with arguments
    (NIL).
See also: 
    The ANSI Standard, Section 7.6.6
```

Unrelated, but is it possible to use [paredit.js](https://github.com/rksm/paredit.js/blob/master/examples/paredit.html) with this?

**Comment by shaunsingh** [comment]
Also unrelated, but does it make more sense to use git for all the sources rather than CDN considering both are available

**Comment by aartaka** [comment]
@shaunsingh, why did you close?

**Comment by aartaka** [comment]
> Unrelated, but is it possible to use [paredit.js](https://github.com/rksm/paredit.js/blob/master/examples/paredit.html) with this?

Yes, I believe it is. But better open a separate issue on that so that we don't lose track of it :)

**Comment by shaunsingh** [comment]
@aartaka I saw you used to have support for 3-pre-release-2 before removing it, I cloned that commit locally and it worked just fine 

> Yes, I believe it is. But better open a separate issue on that so that we don't lose track of it :)

Thanks, will open a seperate issue for it
